### ISSUE TITLE
What is the filename for, is it saved somewhere?

### ISSUE THREAD

**Issue by shanness** [ibm-early-programs/node-red-contrib-pdf-hummus#3]
Hi,
Thanks for this, very useful for me.  Just wondering if the PDF is saved somewhere, I couldn't find it anywhere post running, even though the extraction worked.  I'm basically getting an email with a PDF attachment, and want to extract the dollar totals and forward a message with the total and the PDF as a slack message, so was hoping this would save it for me.

**Comment by chughts** [comment]
@shanness The node makes use of the temp module to process the pdf as a buffer, so it does temporarily save the file on the local system, but it is then cleaned up at the end of the processing. 

As the node puts the output json on `msg.payload`, you will need to save `msg.payload` to something like `msg.rawemail` if you want to make use of it downstream in the flow.

**Comment by shanness** [comment]
Thanks, np, I'll just save the file before passing to you, so it's ready for the slack post after your output.
